version: '3.5'

volumes:
  data:
  db_data:
  db_wal:

services:
  database:
    image: postgres:11
    ports:
      - 5432
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      PGDATA: /data
      POSTGRES_INITDB_WALDIR: /wal
    volumes:
      - db_data:/data
      - db_wal:/wal

  database_mensen:
    image: postgres:11
    environment:
      POSTGRES_DB: mensen
      POSTGRES_USER: mensen
      POSTGRES_PASSWORD: mensen

  database_voertuigen:
    image: postgres:11
    environment:
      POSTGRES_DB: voertuigen
      POSTGRES_USER: voertuigen
      POSTGRES_PASSWORD: voertuigen

  database_boten:
    image: postgres:11
    environment:
      POSTGRES_DB: boten
      POSTGRES_USER: boten
      POSTGRES_PASSWORD: boten

  app:
    image: docker-registry.data.amsterdam.nl/datapunt/waarnemingen-dashboard:${VERSION:-latest}
    build: 
      context: .
      args:
        GF_INSTALL_PLUGINS: >-
          vonage-status-panel,
          flant-statusmap-panel,
          smartmakers-trafficlight-panel,
          grafana-piechart-panel,
          grafana-worldmap-panel,
          farski-blendstat-panel,
          larona-epict-panel,
          agenty-flowcharting-panel,
          pierosavi-imageit-panel
    ports:
      - 3000
    environment:
      - GF_SECURITY_ADMIN_USER=dev
      - GF_SECURITY_ADMIN_PASSWORD=dev

      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=database
      - GF_DATABASE_PORT=5432
      - GF_DATABASE_USER=dev
      - GF_DATABASE_PASSWORD=dev
      - GF_DATABASE_NAME=dev

      - DATABASE_VOERTUIGEN_HOST=database_voertuigen
      - DATABASE_VOERTUIGEN_PORT=5432
      - DATABASE_VOERTUIGEN_USER=voertuigen_read
      - DATABASE_VOERTUIGEN_PASSWORD=voertuigen
      - DATABASE_VOERTUIGEN_DATABASE=voertuigen

      - DATABASE_MENSEN_HOST=database_mensen
      - DATABASE_MENSEN_PORT=15432
      - DATABASE_MENSEN_USER=mensen_read
      - DATABASE_MENSEN_PASSWORD=mensen
      - DATABASE_MENSEN_DATABASE=mensen

      - DATABASE_BOTEN_HOST=database_boten
      - DATABASE_BOTEN_PORT=5432
      - DATABASE_BOTEN_USER=boten_read
      - DATABASE_BOTEN_PASSWORD=boten
      - DATABASE_BOTEN_DATABASE=boten

      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL
      - GF_AUTH_GENERIC_OAUTH_API_URL

      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.sendgrid.net:587
      - GF_SMTP_USER=apikey
      - GF_SMTP_PASSWORD=dev
      - GF_SMTP_FROM_ADDRESS=noreply@amsterdam.nl
      - GF_SMTP_FROM_NAME=Waarnemingen Grafana Dashboard

    volumes:
      - data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - database
      - database_mensen
      - database_voertuigen
      - database_boten
    entrypoint: /deploy/wait-for-it.sh database:5432 --
    command: /run.sh

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./tests:/tests
    environment:
      PYTEST_ADDOPTS:
    depends_on:
      - app
    entrypoint: /deploy/wait-for-it.sh -s -t 30 app:3000 --
    command: pytest
